site_name: Моя документация
dev_addr: 127.0.0.1:8000
livereload: true
theme:
   name: material
   # Палитра цветов (светлая/тёмная тема)
   palette:
      # Светлая тема
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: indigo
        accent: indigo
        toggle:
           icon: material/weather-sunny
           name: "Переключиться на тёмный режим"
      # Тёмная тема
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: indigo
        accent: indigo
        toggle:
           icon: material/weather-night
           name: "Переключиться на светлый режим"

   # Особенности оформления
   features:
      #- navigation.tabs
      - navigation.sections
      - navigation.expand
      #- toc.integrate # Встроенное оглавление
      - search.suggest

extra_css:
   - stylesheets/extra.css
   - docs/Pervoe_podkluchenie/media/

markdown_extensions:
   - attr_list # ← обязательно!
   - admonition
   - toc:
        permalink: true
   - pymdownx.superfences
   - pymdownx.highlight

nav:
   - Главная: index.md
   - Первое подключение к ГИС "Смета ЯНАО": Pervoe_podkluchenie/index.md
   - Настройка КЭП в ЛК ПОЛ "Сервис подотчетного лица" : Crypto_lk_pol.md
   - "RA-LK-2024 ЯНАО": RA-LK-2024_YANAO.md
