site_name: Моя документация

theme:
  name: material
  features:
    # - navigation.tabs      ← удалить
    # - navigation.sections 
    # - toc.integrate
    - navigation.expand
    - search.suggest
    - search.highlight

markdown_extensions:
  - attr_list     # ← обязательно!
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight

nav:
  - Главная: index.md
  - Установка: install-vipnet.md
  - О пользователе: user-guide.md
