dev_addr: 127.0.0.1:8000
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - search.js

markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
      title: Оглавление
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - codehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.tasklist

nav:
  - Главная: index.md
  - Контракты 2019 - 2025: Meropriyatia/svod_gk.md
  - Проекты 2026:
      - Дорожная карта: projects_2006/roadmap.md
      - Справки Образование: 
        - Документация: projects_2006/spravky_educaition.md
        - Комментарии: projects_2006/spravki-obrazovanie-comments.md
      - Личный кабинет и ИИ: lk.md
      - Интеграция с Тезис: tezis.md
      - Отдельные доработки: dopfunction.md
      - Шаблоны и чек-листы: templates.md
  - Заявки и звонки: 
      - Статистика телефонных вызовов: calls.md
      - Статистика по заявкам: zayavky.md
  - Инструкции:
      - Первое подключение к ГИС "Смета ЯНАО": instrukt/Pervoe_podkluchenie.md
      - Настройка УКЭП в ЛК пол: instrukt/Nastroyka-UKEP-v-servise-LK-POL.md
      - Сервис подотчетного лица. Руководство администратора: instrukt/poladmin.md
plugins:
  - search:
      lang: ru
      prebuild_index: true
      separator: '[\s\-–—_]+'
  # - git-revision-date-localized:
  #     timezone: Europe/Moscow
  #     type: date

site_name: Документация ЦБ ОГВ ЯНАО

theme:
  features:
    - content.tooltips
    - navigation.sections
    - navigation.expand
    #- navigation.tabs
    - search.highlight
    - search.suggest
  font:
    code: Roboto Mono
    text: Roboto
  language: ru
  name: material
  palette:
    - accent: indigo
      media: '(prefers-color-scheme: light)'
      primary: indigo
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Переключиться на тёмный режим
    - accent: indigo
      media: '(prefers-color-scheme: dark)'
      primary: indigo
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Переключиться на светлый режим